/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Solna;

import java.util.*;
//import java.util.Scanner;


public class App {

    public static void main(String[] args) {

        int svar, guess = 0, x = 0;
        boolean correct = false;

        svar = (int) (1 + Math.random() * 100);

        Scanner keyboard = new Scanner(System.in);
        System.out.print("Gissa på en siffra mellan 1 och 100: ");

        try{
            guess = keyboard.nextInt();
            correct = true;
        }
        catch (InputMismatchException e) {
            System.out.println("Talet är inte ett heltal. Spelet avslutas");
        }
        if(correct){
            for (int i = 0; i < 9; i++) {
                if(guess >100) {
                    System.out.println("Talet är för stort");
                    System.out.print("Gissa igen: ");
                    //guess = keyboard.nextInt();
                    try{
                        guess = keyboard.nextInt();
                    }
                    catch (InputMismatchException e) {
                        System.out.println("Talet är inte ett heltal. Spelet avslutas");
                        break;
                    }
                    x++;
                }

                if (guess > svar) {
                    System.out.println("Talet är mindre än: " + guess);
                    System.out.print("Gissa igen: ");
                    //guess = keyboard.nextInt();
                    try{
                        guess = keyboard.nextInt();
                    }
                    catch (InputMismatchException e) {
                        System.out.println("Talet är inte ett heltal. Spelet avslutas");
                        break;
                    }
                    x++;
                }

                if (guess < svar) {
                    System.out.println("Talet är större än: " + guess);
                    System.out.print("Gissa igen: ");
                    //guess = keyboard.nextInt();
                    try{
                        guess = keyboard.nextInt();
                    }
                    catch (InputMismatchException e) {
                        System.out.println("Talet är inte ett heltal. Spelet avslutas");
                        break;
                    }
                    x++;
                }

                if (guess == svar) {
                    System.out.println("Grattis, du gissade rätt!");
                    break;
                }
            }
        }

        if(x == 9){
            System.out.println("Synd! Du har gissat 10 gånger! Försök på nytt igen! \nTalet var: " + svar);
        }

    }
}